# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: download
        uses: iamazy/download-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          url: 'https://github.com/GhostenEditor/libmpv-android-build/releases/download/v1.0.0/lib-mpv-release.aar'
          actor: ${{ github.actor }}
          repo: ${{ github.repository }}
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: media3-extension
          path: ./*.aar
